/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as SearchImport } from './routes/search'
import { Route as PracticeImport } from './routes/practice'
import { Route as ContributeImport } from './routes/contribute'
import { Route as AdminImport } from './routes/admin'
import { Route as IndexImport } from './routes/index'
import { Route as SubjectsIndexImport } from './routes/subjects/index'
import { Route as ExamsIndexImport } from './routes/exams/index'
import { Route as AdminIndexImport } from './routes/admin/index'
import { Route as TopicsTopicSlugImport } from './routes/topics/$topicSlug'
import { Route as SubjectsSubjectSlugImport } from './routes/subjects/$subjectSlug'
import { Route as QuestionSetsSlugImport } from './routes/question-sets/$slug'
import { Route as AuthSigninImport } from './routes/auth/signin'
import { Route as AdminSettingsImport } from './routes/admin/settings'
import { Route as AdminScrapingImport } from './routes/admin/scraping'
import { Route as AdminReviewImport } from './routes/admin/review'
import { Route as AdminExamTypesImport } from './routes/admin/exam-types'
import { Route as AdminContributionsImport } from './routes/admin/contributions'
import { Route as AdminAnalyticsImport } from './routes/admin/analytics'
import { Route as ExamsExamSlugIndexImport } from './routes/exams/$examSlug/index'
import { Route as ExamsExamSlugSubjectsSubjectSlugImport } from './routes/exams/$examSlug/subjects/$subjectSlug'
import { Route as QuestionsExamSlugVariantSlugYearSubjectSlugQuestionSlugImport } from './routes/questions/$examSlug.$variantSlug.$year.$subjectSlug.$questionSlug'

// Create/Update Routes

const SearchRoute = SearchImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRoute,
} as any)

const PracticeRoute = PracticeImport.update({
  id: '/practice',
  path: '/practice',
  getParentRoute: () => rootRoute,
} as any)

const ContributeRoute = ContributeImport.update({
  id: '/contribute',
  path: '/contribute',
  getParentRoute: () => rootRoute,
} as any)

const AdminRoute = AdminImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const SubjectsIndexRoute = SubjectsIndexImport.update({
  id: '/subjects/',
  path: '/subjects/',
  getParentRoute: () => rootRoute,
} as any)

const ExamsIndexRoute = ExamsIndexImport.update({
  id: '/exams/',
  path: '/exams/',
  getParentRoute: () => rootRoute,
} as any)

const AdminIndexRoute = AdminIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)

const TopicsTopicSlugRoute = TopicsTopicSlugImport.update({
  id: '/topics/$topicSlug',
  path: '/topics/$topicSlug',
  getParentRoute: () => rootRoute,
} as any)

const SubjectsSubjectSlugRoute = SubjectsSubjectSlugImport.update({
  id: '/subjects/$subjectSlug',
  path: '/subjects/$subjectSlug',
  getParentRoute: () => rootRoute,
} as any)

const QuestionSetsSlugRoute = QuestionSetsSlugImport.update({
  id: '/question-sets/$slug',
  path: '/question-sets/$slug',
  getParentRoute: () => rootRoute,
} as any)

const AuthSigninRoute = AuthSigninImport.update({
  id: '/auth/signin',
  path: '/auth/signin',
  getParentRoute: () => rootRoute,
} as any)

const AdminSettingsRoute = AdminSettingsImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)

const AdminScrapingRoute = AdminScrapingImport.update({
  id: '/scraping',
  path: '/scraping',
  getParentRoute: () => AdminRoute,
} as any)

const AdminReviewRoute = AdminReviewImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => AdminRoute,
} as any)

const AdminExamTypesRoute = AdminExamTypesImport.update({
  id: '/exam-types',
  path: '/exam-types',
  getParentRoute: () => AdminRoute,
} as any)

const AdminContributionsRoute = AdminContributionsImport.update({
  id: '/contributions',
  path: '/contributions',
  getParentRoute: () => AdminRoute,
} as any)

const AdminAnalyticsRoute = AdminAnalyticsImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AdminRoute,
} as any)

const ExamsExamSlugIndexRoute = ExamsExamSlugIndexImport.update({
  id: '/exams/$examSlug/',
  path: '/exams/$examSlug/',
  getParentRoute: () => rootRoute,
} as any)

const ExamsExamSlugSubjectsSubjectSlugRoute =
  ExamsExamSlugSubjectsSubjectSlugImport.update({
    id: '/exams/$examSlug/subjects/$subjectSlug',
    path: '/exams/$examSlug/subjects/$subjectSlug',
    getParentRoute: () => rootRoute,
  } as any)

const QuestionsExamSlugVariantSlugYearSubjectSlugQuestionSlugRoute =
  QuestionsExamSlugVariantSlugYearSubjectSlugQuestionSlugImport.update({
    id: '/questions/$examSlug/$variantSlug/$year/$subjectSlug/$questionSlug',
    path: '/questions/$examSlug/$variantSlug/$year/$subjectSlug/$questionSlug',
    getParentRoute: () => rootRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminImport
      parentRoute: typeof rootRoute
    }
    '/contribute': {
      id: '/contribute'
      path: '/contribute'
      fullPath: '/contribute'
      preLoaderRoute: typeof ContributeImport
      parentRoute: typeof rootRoute
    }
    '/practice': {
      id: '/practice'
      path: '/practice'
      fullPath: '/practice'
      preLoaderRoute: typeof PracticeImport
      parentRoute: typeof rootRoute
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchImport
      parentRoute: typeof rootRoute
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsImport
      parentRoute: typeof AdminImport
    }
    '/admin/contributions': {
      id: '/admin/contributions'
      path: '/contributions'
      fullPath: '/admin/contributions'
      preLoaderRoute: typeof AdminContributionsImport
      parentRoute: typeof AdminImport
    }
    '/admin/exam-types': {
      id: '/admin/exam-types'
      path: '/exam-types'
      fullPath: '/admin/exam-types'
      preLoaderRoute: typeof AdminExamTypesImport
      parentRoute: typeof AdminImport
    }
    '/admin/review': {
      id: '/admin/review'
      path: '/review'
      fullPath: '/admin/review'
      preLoaderRoute: typeof AdminReviewImport
      parentRoute: typeof AdminImport
    }
    '/admin/scraping': {
      id: '/admin/scraping'
      path: '/scraping'
      fullPath: '/admin/scraping'
      preLoaderRoute: typeof AdminScrapingImport
      parentRoute: typeof AdminImport
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsImport
      parentRoute: typeof AdminImport
    }
    '/auth/signin': {
      id: '/auth/signin'
      path: '/auth/signin'
      fullPath: '/auth/signin'
      preLoaderRoute: typeof AuthSigninImport
      parentRoute: typeof rootRoute
    }
    '/question-sets/$slug': {
      id: '/question-sets/$slug'
      path: '/question-sets/$slug'
      fullPath: '/question-sets/$slug'
      preLoaderRoute: typeof QuestionSetsSlugImport
      parentRoute: typeof rootRoute
    }
    '/subjects/$subjectSlug': {
      id: '/subjects/$subjectSlug'
      path: '/subjects/$subjectSlug'
      fullPath: '/subjects/$subjectSlug'
      preLoaderRoute: typeof SubjectsSubjectSlugImport
      parentRoute: typeof rootRoute
    }
    '/topics/$topicSlug': {
      id: '/topics/$topicSlug'
      path: '/topics/$topicSlug'
      fullPath: '/topics/$topicSlug'
      preLoaderRoute: typeof TopicsTopicSlugImport
      parentRoute: typeof rootRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexImport
      parentRoute: typeof AdminImport
    }
    '/exams/': {
      id: '/exams/'
      path: '/exams'
      fullPath: '/exams'
      preLoaderRoute: typeof ExamsIndexImport
      parentRoute: typeof rootRoute
    }
    '/subjects/': {
      id: '/subjects/'
      path: '/subjects'
      fullPath: '/subjects'
      preLoaderRoute: typeof SubjectsIndexImport
      parentRoute: typeof rootRoute
    }
    '/exams/$examSlug/': {
      id: '/exams/$examSlug/'
      path: '/exams/$examSlug'
      fullPath: '/exams/$examSlug'
      preLoaderRoute: typeof ExamsExamSlugIndexImport
      parentRoute: typeof rootRoute
    }
    '/exams/$examSlug/subjects/$subjectSlug': {
      id: '/exams/$examSlug/subjects/$subjectSlug'
      path: '/exams/$examSlug/subjects/$subjectSlug'
      fullPath: '/exams/$examSlug/subjects/$subjectSlug'
      preLoaderRoute: typeof ExamsExamSlugSubjectsSubjectSlugImport
      parentRoute: typeof rootRoute
    }
    '/questions/$examSlug/$variantSlug/$year/$subjectSlug/$questionSlug': {
      id: '/questions/$examSlug/$variantSlug/$year/$subjectSlug/$questionSlug'
      path: '/questions/$examSlug/$variantSlug/$year/$subjectSlug/$questionSlug'
      fullPath: '/questions/$examSlug/$variantSlug/$year/$subjectSlug/$questionSlug'
      preLoaderRoute: typeof QuestionsExamSlugVariantSlugYearSubjectSlugQuestionSlugImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

interface AdminRouteChildren {
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminContributionsRoute: typeof AdminContributionsRoute
  AdminExamTypesRoute: typeof AdminExamTypesRoute
  AdminReviewRoute: typeof AdminReviewRoute
  AdminScrapingRoute: typeof AdminScrapingRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminContributionsRoute: AdminContributionsRoute,
  AdminExamTypesRoute: AdminExamTypesRoute,
  AdminReviewRoute: AdminReviewRoute,
  AdminScrapingRoute: AdminScrapingRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/contribute': typeof ContributeRoute
  '/practice': typeof PracticeRoute
  '/search': typeof SearchRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/contributions': typeof AdminContributionsRoute
  '/admin/exam-types': typeof AdminExamTypesRoute
  '/admin/review': typeof AdminReviewRoute
  '/admin/scraping': typeof AdminScrapingRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/auth/signin': typeof AuthSigninRoute
  '/question-sets/$slug': typeof QuestionSetsSlugRoute
  '/subjects/$subjectSlug': typeof SubjectsSubjectSlugRoute
  '/topics/$topicSlug': typeof TopicsTopicSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/exams': typeof ExamsIndexRoute
  '/subjects': typeof SubjectsIndexRoute
  '/exams/$examSlug': typeof ExamsExamSlugIndexRoute
  '/exams/$examSlug/subjects/$subjectSlug': typeof ExamsExamSlugSubjectsSubjectSlugRoute
  '/questions/$examSlug/$variantSlug/$year/$subjectSlug/$questionSlug': typeof QuestionsExamSlugVariantSlugYearSubjectSlugQuestionSlugRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contribute': typeof ContributeRoute
  '/practice': typeof PracticeRoute
  '/search': typeof SearchRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/contributions': typeof AdminContributionsRoute
  '/admin/exam-types': typeof AdminExamTypesRoute
  '/admin/review': typeof AdminReviewRoute
  '/admin/scraping': typeof AdminScrapingRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/auth/signin': typeof AuthSigninRoute
  '/question-sets/$slug': typeof QuestionSetsSlugRoute
  '/subjects/$subjectSlug': typeof SubjectsSubjectSlugRoute
  '/topics/$topicSlug': typeof TopicsTopicSlugRoute
  '/admin': typeof AdminIndexRoute
  '/exams': typeof ExamsIndexRoute
  '/subjects': typeof SubjectsIndexRoute
  '/exams/$examSlug': typeof ExamsExamSlugIndexRoute
  '/exams/$examSlug/subjects/$subjectSlug': typeof ExamsExamSlugSubjectsSubjectSlugRoute
  '/questions/$examSlug/$variantSlug/$year/$subjectSlug/$questionSlug': typeof QuestionsExamSlugVariantSlugYearSubjectSlugQuestionSlugRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/contribute': typeof ContributeRoute
  '/practice': typeof PracticeRoute
  '/search': typeof SearchRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/contributions': typeof AdminContributionsRoute
  '/admin/exam-types': typeof AdminExamTypesRoute
  '/admin/review': typeof AdminReviewRoute
  '/admin/scraping': typeof AdminScrapingRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/auth/signin': typeof AuthSigninRoute
  '/question-sets/$slug': typeof QuestionSetsSlugRoute
  '/subjects/$subjectSlug': typeof SubjectsSubjectSlugRoute
  '/topics/$topicSlug': typeof TopicsTopicSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/exams/': typeof ExamsIndexRoute
  '/subjects/': typeof SubjectsIndexRoute
  '/exams/$examSlug/': typeof ExamsExamSlugIndexRoute
  '/exams/$examSlug/subjects/$subjectSlug': typeof ExamsExamSlugSubjectsSubjectSlugRoute
  '/questions/$examSlug/$variantSlug/$year/$subjectSlug/$questionSlug': typeof QuestionsExamSlugVariantSlugYearSubjectSlugQuestionSlugRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/contribute'
    | '/practice'
    | '/search'
    | '/admin/analytics'
    | '/admin/contributions'
    | '/admin/exam-types'
    | '/admin/review'
    | '/admin/scraping'
    | '/admin/settings'
    | '/auth/signin'
    | '/question-sets/$slug'
    | '/subjects/$subjectSlug'
    | '/topics/$topicSlug'
    | '/admin/'
    | '/exams'
    | '/subjects'
    | '/exams/$examSlug'
    | '/exams/$examSlug/subjects/$subjectSlug'
    | '/questions/$examSlug/$variantSlug/$year/$subjectSlug/$questionSlug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contribute'
    | '/practice'
    | '/search'
    | '/admin/analytics'
    | '/admin/contributions'
    | '/admin/exam-types'
    | '/admin/review'
    | '/admin/scraping'
    | '/admin/settings'
    | '/auth/signin'
    | '/question-sets/$slug'
    | '/subjects/$subjectSlug'
    | '/topics/$topicSlug'
    | '/admin'
    | '/exams'
    | '/subjects'
    | '/exams/$examSlug'
    | '/exams/$examSlug/subjects/$subjectSlug'
    | '/questions/$examSlug/$variantSlug/$year/$subjectSlug/$questionSlug'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/contribute'
    | '/practice'
    | '/search'
    | '/admin/analytics'
    | '/admin/contributions'
    | '/admin/exam-types'
    | '/admin/review'
    | '/admin/scraping'
    | '/admin/settings'
    | '/auth/signin'
    | '/question-sets/$slug'
    | '/subjects/$subjectSlug'
    | '/topics/$topicSlug'
    | '/admin/'
    | '/exams/'
    | '/subjects/'
    | '/exams/$examSlug/'
    | '/exams/$examSlug/subjects/$subjectSlug'
    | '/questions/$examSlug/$variantSlug/$year/$subjectSlug/$questionSlug'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  ContributeRoute: typeof ContributeRoute
  PracticeRoute: typeof PracticeRoute
  SearchRoute: typeof SearchRoute
  AuthSigninRoute: typeof AuthSigninRoute
  QuestionSetsSlugRoute: typeof QuestionSetsSlugRoute
  SubjectsSubjectSlugRoute: typeof SubjectsSubjectSlugRoute
  TopicsTopicSlugRoute: typeof TopicsTopicSlugRoute
  ExamsIndexRoute: typeof ExamsIndexRoute
  SubjectsIndexRoute: typeof SubjectsIndexRoute
  ExamsExamSlugIndexRoute: typeof ExamsExamSlugIndexRoute
  ExamsExamSlugSubjectsSubjectSlugRoute: typeof ExamsExamSlugSubjectsSubjectSlugRoute
  QuestionsExamSlugVariantSlugYearSubjectSlugQuestionSlugRoute: typeof QuestionsExamSlugVariantSlugYearSubjectSlugQuestionSlugRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  ContributeRoute: ContributeRoute,
  PracticeRoute: PracticeRoute,
  SearchRoute: SearchRoute,
  AuthSigninRoute: AuthSigninRoute,
  QuestionSetsSlugRoute: QuestionSetsSlugRoute,
  SubjectsSubjectSlugRoute: SubjectsSubjectSlugRoute,
  TopicsTopicSlugRoute: TopicsTopicSlugRoute,
  ExamsIndexRoute: ExamsIndexRoute,
  SubjectsIndexRoute: SubjectsIndexRoute,
  ExamsExamSlugIndexRoute: ExamsExamSlugIndexRoute,
  ExamsExamSlugSubjectsSubjectSlugRoute: ExamsExamSlugSubjectsSubjectSlugRoute,
  QuestionsExamSlugVariantSlugYearSubjectSlugQuestionSlugRoute:
    QuestionsExamSlugVariantSlugYearSubjectSlugQuestionSlugRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/admin",
        "/contribute",
        "/practice",
        "/search",
        "/auth/signin",
        "/question-sets/$slug",
        "/subjects/$subjectSlug",
        "/topics/$topicSlug",
        "/exams/",
        "/subjects/",
        "/exams/$examSlug/",
        "/exams/$examSlug/subjects/$subjectSlug",
        "/questions/$examSlug/$variantSlug/$year/$subjectSlug/$questionSlug"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/admin": {
      "filePath": "admin.tsx",
      "children": [
        "/admin/analytics",
        "/admin/contributions",
        "/admin/exam-types",
        "/admin/review",
        "/admin/scraping",
        "/admin/settings",
        "/admin/"
      ]
    },
    "/contribute": {
      "filePath": "contribute.tsx"
    },
    "/practice": {
      "filePath": "practice.tsx"
    },
    "/search": {
      "filePath": "search.tsx"
    },
    "/admin/analytics": {
      "filePath": "admin/analytics.tsx",
      "parent": "/admin"
    },
    "/admin/contributions": {
      "filePath": "admin/contributions.tsx",
      "parent": "/admin"
    },
    "/admin/exam-types": {
      "filePath": "admin/exam-types.tsx",
      "parent": "/admin"
    },
    "/admin/review": {
      "filePath": "admin/review.tsx",
      "parent": "/admin"
    },
    "/admin/scraping": {
      "filePath": "admin/scraping.tsx",
      "parent": "/admin"
    },
    "/admin/settings": {
      "filePath": "admin/settings.tsx",
      "parent": "/admin"
    },
    "/auth/signin": {
      "filePath": "auth/signin.tsx"
    },
    "/question-sets/$slug": {
      "filePath": "question-sets/$slug.tsx"
    },
    "/subjects/$subjectSlug": {
      "filePath": "subjects/$subjectSlug.tsx"
    },
    "/topics/$topicSlug": {
      "filePath": "topics/$topicSlug.tsx"
    },
    "/admin/": {
      "filePath": "admin/index.tsx",
      "parent": "/admin"
    },
    "/exams/": {
      "filePath": "exams/index.tsx"
    },
    "/subjects/": {
      "filePath": "subjects/index.tsx"
    },
    "/exams/$examSlug/": {
      "filePath": "exams/$examSlug/index.tsx"
    },
    "/exams/$examSlug/subjects/$subjectSlug": {
      "filePath": "exams/$examSlug/subjects/$subjectSlug.tsx"
    },
    "/questions/$examSlug/$variantSlug/$year/$subjectSlug/$questionSlug": {
      "filePath": "questions/$examSlug.$variantSlug.$year.$subjectSlug.$questionSlug.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
